services:
  laravel.test:
    build:
      args:
        WWWGROUP: "${WWWGROUP}"
      context: "./vendor/laravel/sail/runtimes/8.3"
      dockerfile: "Dockerfile"

    depends_on:
      - "mysql"

    environment:
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
      LARAVEL_SAIL: 1
      WWWUSER: "${WWWUSER}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    image: "sail-8.3/app"

    networks:
      - "sail"

    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"

    volumes:
      - ".:/var/www/html"

  mysql:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USERNAME}"

    healthcheck:
      test:
        - "CMD"
        - "mysqladmin"
        - "ping"
        - "-p${DB_PASSWORD}"
      retries: 3
      timeout: "5s"

    image: "mysql/mysql-server:8.0"

    networks:
      - "sail"

    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"

    volumes:
      - "sail-mysql:/var/lib/mysql"
      - "./vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"

networks:
  sail:
    driver: "bridge"

volumes:
  sail-mysql:
    driver: "local"
