# https://docs.github.com/en/actions

name: "Renew"

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 1 1 *"

jobs:
  license:
    name: "License"

    runs-on: "ubuntu-latest"

    timeout-minutes: 5

    strategy:
      matrix:
        php-version:
          - "8.3"

        dependencies:
          - "locked"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4.1.2"
        with:
          token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"

      - name: "Set up PHP"
        uses: "shivammathur/setup-php@2.30.0"
        with:
          coverage: "none"
          extensions: "none, ctype, curl, dom, fileinfo, iconv, intl, json, mbstring, pdo, pdo_mysql, phar, simplexml, tokenizer, xml, xmlwriter"
          php-version: "${{ matrix.php-version }}"

      - name: "Set up problem matchers for PHP"
        run: "echo \"::add-matcher::${{ runner.tool_cache }}/php.json\""

      - name: "Validate composer.json and composer.lock"
        run: "composer validate --ansi --strict"

      - name: "Determine composer cache directory"
        uses: "ergebnis/.github/actions/composer/determine-cache-directory@1.9.0"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v4.0.1"
        with:
          path: "${{ env.COMPOSER_CACHE_DIR }}"
          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

      - name: "Install ${{ matrix.dependencies }} dependencies with composer"
        uses: "ergebnis/.github/actions/composer/install@1.9.0"
        with:
          dependencies: "${{ matrix.dependencies }}"

      - name: "Cache cache directory for laravel/pint"
        uses: "actions/cache@v4.0.1"
        with:
          path: ".build/pint/"
          key: "php-${{ matrix.php-version }}-pint-${{ github.ref_name }}"
          restore-keys: |
            php-${{ matrix.php-version }}-pint-main
            php-${{ matrix.php-version }}-pint-

      - name: "Run laravel/pint"
        run: "vendor/bin/pint --ansi --config=pint.json -v"

      - name: "Commit modified files"
        uses: "stefanzweifel/git-auto-commit-action@v5.0.0"
        with:
          commit_author: "ergebnis-bot <bot@ergebn.is>"
          commit_message: "Enhancement: Update license year"
          commit_user_email: "bot@ergebn.is"
          commit_user_name: "ergebnis-bot"
